# This is a basic workflow to help you get started with Actions

name: Debug workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  session:
    runs-on: ubuntu-latest
    environment: debug

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get -y install openssh-server openssh-client tmux
          sudo systemctl start ssh
      - name: Write private key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_AUTHORIZED_KEY: ${{ secrets.SSH_AUTHORIZED_KEY }}
        run: |
          mkdir -p -m 0700 "${HOME}/.ssh"
          chmod -R u+rwX,go-rwx "${HOME}/.ssh"
          echo "$SSH_KEY" > "${HOME}/.ssh/id_ed25519"
          echo "$SSH_AUTHORIZED_KEY" > "${HOME}/.ssh/authorized_keys"
      - name: SSH Forwarding
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_REMOTE: ${{ secrets.SSH_REMOTE }}
        run: |
          ssh -o StrictHostKeyChecking=no -N -R "${SSH_REMOTE}" -p "${SSH_PORT}" "${SSH_HOST}" 1>/dev/null 2>&1 &
          sleep 7200
